version: "3"
services:
  api:
    environment:
      - PORT=3000
      - MONGO_CONNECTION_STRING=mongodb://database:27017/SLTest
    build: API
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./API/:/usr/src/app
  database:
    image: "mongo"
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  mongodb_data_container:
