version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb
  api:
    environment:
      - PORT=3000
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017/SLTest
    build: API
    ports:
      - "3000:3000"
    volumes:
      - ./API/:/usr/src/app
volumes:
  mongodb_data_container:
